#!/usr/bin/env python3
"""
YouTube Upload via Selenium + Chrome real (perfil do usuário já logado).
Abre Chrome com perfil existente usando remote debugging.
"""

import time
import sys
import os
import subprocess
import shutil

VIDEO_PATH = sys.argv[1] if len(sys.argv) > 1 else "/Users/maiconjonathamartinsdasilva/Desktop/flow_celestial.mp4"
TITLE = sys.argv[2] if len(sys.argv) > 2 else "Flow Celestial | AI Generated Music Video"
DESCRIPTION = sys.argv[3] if len(sys.argv) > 3 else "Video generated by AI ecosystem. Flow Celestial - uma experiencia visual e sonora criada por inteligencia artificial.\n\n#AI #Music #FlowCelestial #AIVideo"

CHROME_PATH = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
CHROMEDRIVER_PATH = "/Users/maiconjonathamartinsdasilva/.wdm/drivers/chromedriver/mac64/145.0.7632.117/chromedriver-mac-arm64/chromedriver"
CHROME_PROFILE = os.path.expanduser("~/Library/Application Support/Google/Chrome")
# Usar perfil temporário copiado para não conflitar com Chrome aberto
TEMP_PROFILE = "/tmp/chrome_youtube_profile"

def main():
    print(f"[*] Video: {VIDEO_PATH}")
    print(f"[*] Title: {TITLE}")
    
    if not os.path.exists(VIDEO_PATH):
        print(f"[!] Arquivo nao encontrado: {VIDEO_PATH}")
        return
    
    from selenium import webdriver
    from selenium.webdriver.chrome.service import Service
    from selenium.webdriver.chrome.options import Options
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.support import expected_conditions as EC
    from selenium.webdriver.common.keys import Keys
    
    # Copiar perfil do Chrome para temp (evita lock conflict)
    print("[*] Preparando perfil do Chrome...")
    if os.path.exists(TEMP_PROFILE):
        shutil.rmtree(TEMP_PROFILE, ignore_errors=True)
    
    # Copiar apenas o Default profile (mais rápido)
    os.makedirs(f"{TEMP_PROFILE}/Default", exist_ok=True)
    
    # Copiar arquivos essenciais de cookies e login
    essential_files = [
        "Cookies", "Login Data", "Web Data", "Preferences", 
        "Secure Preferences", "Local State"
    ]
    
    for f in essential_files:
        src = f"{CHROME_PROFILE}/Default/{f}"
        dst = f"{TEMP_PROFILE}/Default/{f}"
        if os.path.exists(src):
            shutil.copy2(src, dst)
            print(f"  Copiado: {f}")
    
    # Copiar Local State do diretório raiz
    local_state_src = f"{CHROME_PROFILE}/Local State"
    local_state_dst = f"{TEMP_PROFILE}/Local State"
    if os.path.exists(local_state_src):
        shutil.copy2(local_state_src, local_state_dst)
        print("  Copiado: Local State (root)")
    
    # Configurar Chrome
    options = Options()
    options.binary_location = CHROME_PATH
    options.add_argument(f"--user-data-dir={TEMP_PROFILE}")
    options.add_argument("--profile-directory=Default")
    options.add_argument("--no-first-run")
    options.add_argument("--no-default-browser-check")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)
    options.add_argument("--window-size=1280,900")
    
    service = Service(CHROMEDRIVER_PATH)
    
    print("[*] Abrindo Chrome...")
    driver = webdriver.Chrome(service=service, options=options)
    
    # Remover flag de webdriver
    driver.execute_cdp_cmd("Page.addScriptToEvaluateOnNewDocument", {
        "source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
    })
    
    try:
        # Ir para YouTube Studio
        print("[*] Abrindo YouTube Studio...")
        driver.get("https://studio.youtube.com")
        time.sleep(5)
        
        current_url = driver.current_url
        print(f"[*] URL: {current_url}")
        
        if "accounts.google.com" in current_url or "signin" in current_url.lower():
            print("[!] Nao esta logado! Os cookies nao foram transferidos corretamente.")
            print("[*] Tentando abordagem alternativa: YouTube upload direto...")
            
            # Tentar ir direto para upload
            driver.get("https://www.youtube.com")
            time.sleep(5)
            
            current_url = driver.current_url
            print(f"[*] YouTube URL: {current_url}")
            
            if "accounts.google.com" in current_url or "signin" in current_url.lower():
                print("[!] Definitivamente nao logado. Cookies do Chrome estao encriptados.")
                print("[*] Vou tentar usar Playwright com Chromium (nao Firefox)...")
                driver.quit()
                
                # Fallback: usar Playwright com Chromium
                return try_playwright_chromium()
            
        print("[+] Logado no YouTube!")
        
        # Navegar para upload
        print("[*] Indo para pagina de upload...")
        driver.get("https://www.youtube.com/upload")
        time.sleep(5)
        
        # Upload arquivo
        print(f"[*] Fazendo upload: {VIDEO_PATH}")
        try:
            file_input = WebDriverWait(driver, 15).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, 'input[type="file"]'))
            )
            file_input.send_keys(VIDEO_PATH)
            print("[+] Arquivo enviado!")
        except Exception as e:
            print(f"[!] Erro upload: {e}")
            time.sleep(120)
            driver.quit()
            return
        
        # Aguardar dialog
        time.sleep(8)
        
        # Preencher título
        print(f"[*] Preenchendo titulo...")
        try:
            title_box = WebDriverWait(driver, 15).until(
                EC.element_to_be_clickable((By.CSS_SELECTOR, '#textbox[aria-label]'))
            )
            title_box.click()
            time.sleep(0.5)
            # Selecionar tudo e substituir
            title_box.send_keys(Keys.COMMAND + "a")
            time.sleep(0.3)
            title_box.send_keys(Keys.BACKSPACE)
            time.sleep(0.3)
            title_box.send_keys(TITLE)
            print("[+] Titulo preenchido!")
        except Exception as e:
            print(f"[!] Erro titulo: {e}")
        
        time.sleep(1)
        
        # Preencher descrição
        print("[*] Preenchendo descricao...")
        try:
            desc_boxes = driver.find_elements(By.CSS_SELECTOR, '#textbox')
            if len(desc_boxes) >= 2:
                desc_boxes[1].click()
                time.sleep(0.5)
                desc_boxes[1].send_keys(DESCRIPTION)
                print("[+] Descricao preenchida!")
        except Exception as e:
            print(f"[!] Erro descricao: {e}")
        
        time.sleep(1)
        
        # Marcar "Não é para crianças"
        try:
            not_kids = driver.find_elements(By.CSS_SELECTOR, 'tp-yt-paper-radio-button[name="NOT_MADE_FOR_KIDS"]')
            if not_kids:
                not_kids[0].click()
                print("[+] NOT_MADE_FOR_KIDS marcado")
        except:
            pass
        
        time.sleep(1)
        
        # Avançar etapas
        for step in range(3):
            try:
                next_btn = driver.find_element(By.CSS_SELECTOR, '#next-button')
                next_btn.click()
                print(f"[+] Avancou etapa {step+1}")
                time.sleep(2)
            except:
                pass
        
        # Selecionar PÚBLICO
        print("[*] Selecionando PUBLICO...")
        try:
            public = driver.find_elements(By.CSS_SELECTOR, 'tp-yt-paper-radio-button[name="PUBLIC"]')
            if public:
                public[0].click()
                print("[+] PUBLICO selecionado!")
        except:
            pass
        
        time.sleep(2)
        
        # Aguardar upload concluir
        print("[*] Aguardando upload concluir...")
        for i in range(120):
            try:
                done_btn = driver.find_element(By.CSS_SELECTOR, '#done-button')
                is_disabled = done_btn.get_attribute("aria-disabled")
                if is_disabled != "true":
                    print("[+] Upload concluido!")
                    break
            except:
                pass
            if i % 6 == 0:
                print(f"  Aguardando... ({i*5}s)")
            time.sleep(5)
        
        # PUBLICAR
        print("[*] PUBLICANDO...")
        try:
            done_btn = driver.find_element(By.CSS_SELECTOR, '#done-button')
            done_btn.click()
            print("[+] PUBLICADO!")
            time.sleep(5)
            
            # Capturar link
            try:
                links = driver.find_elements(By.CSS_SELECTOR, 'a[href*="youtu.be"], a[href*="watch?v="]')
                for link in links:
                    href = link.get_attribute("href")
                    if href:
                        print(f"\n{'='*60}")
                        print(f"VIDEO PUBLICADO!")
                        print(f"Link: {href}")
                        print(f"{'='*60}\n")
                        break
            except:
                pass
        except Exception as e:
            print(f"[!] Erro publicar: {e}")
        
        print("[*] Aguardando 30s...")
        time.sleep(30)
        
    finally:
        driver.quit()
        print("[*] Chrome fechado")


def try_playwright_chromium():
    """Fallback: usar Playwright com Chromium e cookies exportadas via JS"""
    import asyncio
    from playwright.async_api import async_playwright
    
    async def run():
        async with async_playwright() as p:
            # Usar Chromium (não Firefox) - Google aceita melhor
            browser = await p.chromium.launch(
                headless=False,
                args=[
                    "--disable-blink-features=AutomationControlled",
                    "--no-first-run",
                ],
                slow_mo=300,
            )
            
            context = await browser.new_context(
                viewport={"width": 1280, "height": 900},
                locale="pt-BR",
            )
            
            # Remover detecção de automação
            await context.add_init_script("""
                Object.defineProperty(navigator, 'webdriver', {get: () => undefined});
                delete navigator.__proto__.webdriver;
            """)
            
            page = await context.new_page()
            
            print("[*] Abrindo YouTube com Chromium...")
            await page.goto("https://accounts.google.com", wait_until="networkidle", timeout=60000)
            await asyncio.sleep(3)
            
            print("[*] Voce precisa fazer login manualmente neste navegador.")
            print("[*] Aguardando ate 5 minutos para login...")
            
            # Aguardar login (verificar se saiu da página de login)
            for i in range(60):
                url = page.url
                if "myaccount.google.com" in url or "youtube.com" in url:
                    print("[+] Login detectado!")
                    break
                await asyncio.sleep(5)
                if i % 6 == 0:
                    print(f"  Aguardando login... ({i*5}s) URL: {url[:60]}")
            
            # Ir para YouTube Studio
            await page.goto("https://studio.youtube.com", wait_until="networkidle", timeout=60000)
            await asyncio.sleep(4)
            
            url = page.url
            print(f"[*] URL: {url}")
            
            if "accounts.google.com" in url:
                print("[!] Ainda nao logado. Abortando.")
                await browser.close()
                return
            
            print("[+] No YouTube Studio!")
            
            # Upload...
            create_btn = page.locator('#create-icon')
            if await create_btn.count() > 0:
                await create_btn.first.click()
                await asyncio.sleep(2)
            
            upload_item = page.locator('tp-yt-paper-item').filter(has_text="Enviar")
            if await upload_item.count() > 0:
                await upload_item.first.click()
                await asyncio.sleep(3)
            
            file_input = page.locator('input[type="file"]')
            if await file_input.count() > 0:
                await file_input.first.set_input_files(VIDEO_PATH)
                print("[+] Upload iniciado!")
            
            await asyncio.sleep(8)
            
            # Título
            title_box = page.locator('#textbox').first
            await title_box.click()
            await page.keyboard.press("Meta+a")
            await page.keyboard.press("Backspace")
            await page.keyboard.type(TITLE, delay=25)
            
            # Descrição
            desc_boxes = page.locator('#textbox')
            if await desc_boxes.count() >= 2:
                await desc_boxes.nth(1).click()
                await page.keyboard.type(DESCRIPTION, delay=15)
            
            # Not kids
            not_kids = page.locator('[name="NOT_MADE_FOR_KIDS"]')
            if await not_kids.count() > 0:
                await not_kids.first.click()
            
            # Next x3
            for _ in range(3):
                next_btn = page.locator('#next-button')
                if await next_btn.count() > 0:
                    await next_btn.first.click()
                    await asyncio.sleep(2)
            
            # Public
            public = page.locator('[name="PUBLIC"]')
            if await public.count() > 0:
                await public.first.click()
            
            await asyncio.sleep(2)
            
            # Wait for upload
            for i in range(120):
                try:
                    done_btn = page.locator('#done-button')
                    disabled = await done_btn.first.get_attribute("aria-disabled")
                    if disabled != "true":
                        print("[+] Upload pronto!")
                        break
                except:
                    pass
                if i % 6 == 0:
                    print(f"  Aguardando upload... ({i*5}s)")
                await asyncio.sleep(5)
            
            # Publish
            done_btn = page.locator('#done-button')
            await done_btn.first.click()
            print("[+] PUBLICADO!")
            
            await asyncio.sleep(10)
            
            try:
                link = await page.locator('a[href*="youtu.be"], a[href*="watch"]').first.get_attribute("href", timeout=5000)
                print(f"\nLink: {link}\n")
            except:
                pass
            
            await asyncio.sleep(30)
            await browser.close()
    
    asyncio.run(run())


if __name__ == "__main__":
    main()
